### ISSUE TITLE
Optimize ISlideCollection.Add()

### ISSUE THREAD

**Issue by adamshakhabov** [ShapeCrawler/ShapeCrawler#274] opened 2022-08-30 19:49 UTC
### Discussed in https://github.com/ShapeCrawler/ShapeCrawler/discussions/273

<div type='discussions-op-text'>

<sup>Originally posted by **shanaki** August 29, 2022</sup>
When insert a slide from source presentation file and add to target presentation file,
it looks like ppt/media contains duplicated images.

Originally, source.pptx has one image file(in slide master), I can confirm it in ppt/media after remaned to source.zip and unzip it.
target.pptx has also one image file(in slide master), I can also confirm it in ppt/media after remaned to target.zip and unzip it.
Both image files are identical.

Then, run following program.

using IPresentation source = SCPresentation.Open("C:\\testdir\\source.pptx", true);
using IPresentation dest = SCPresentation.Open("C:\\testdir\\target.pptx", true);

// Copy the first slide from source and add to the last slide in dest
 ISlide copyingSlide = source.Slides[0];
 dest.Slides.Add(copyingSlide);
 dest.Save();

As a result, target.pptx has two image files in ppt/media. They are duplicated ones.(the same image files)
It looks like image in slide master of source presentation is copied to the target presentation.
Is this intentional behavior or kind of an issue?

[testfiles.zip](https://github.com/ShapeCrawler/ShapeCrawler/files/9442197/testfiles.zip)

I also found that ppt\presentation.xml contains weird relationship id like this in target presentation file after rename target.zip and unzip it.
<p:sldId r:id="rId2" id="256"/>
<p:sldId r:id="rId3" id="257"/>
<p:sldId r:id="rId4" id="258"/>
<p:sldId r:id="R94ea77bcca954761" id="259"/>

I'm not sure this is related to the above issue, or separated issue.
</div>

**Comment by shanaki** [comment] 2022-09-02 00:42
When open target.pptx in PowerPoint and just save it. Then, it looks like issue is gone away. For example, media file is just one. This is interesting thing.

**Comment by adamshakhabov** [comment] 2022-11-27 21:19
Fixed. It will be available in the next v0.38.0 version.

**Comment by shanaki** [comment] 2023-02-22 15:34
I verified that duplicated image issue is fixed in the latest version(0.41.4). However, ppt/presentation.xml issue is still reproducible. Is it NOT fixed yet?

**Comment by adamshakhabov** [comment] 2023-02-23 19:35
No, it is not fixed. Will do it.

**Comment by adamshakhabov** [comment] 2023-02-26 11:16
Generating inconsistent RelationshipId also has been fixed and will be available in the next version.

**Closed** 2023-03-17 23:31 UTC
Labels: edit
