### ISSUE TITLE
Unable to remove shapes

### ISSUE THREAD

**Issue by pnoffke64** [ShapeCrawler/ShapeCrawler#735] opened 2024-08-15 15:45 UTC
Unable to remove shapes from a ShapeCrawler Presentation

```
        var pres = new ShapeCrawler.Presentation();

        var shapes = pres.Slides[0].Shapes;

        shapes.AddRectangle(x: 50, y: 60, width: 100, height: 70);

        shapes.Remove(shapes.Last());
```

Error will be thrown on the last line.

Taking a peek into the SC codebase, I see the remove method in question seems to always throw an exception

```
public void Remove(IShape shape)
{
    if (this.shapes.Any(x => x != shape))
    {
        throw new SCException("Shape is not found.");
    }

    if (shape is IRemoveable removeable)
    {
        removeable.Remove();
    }

    throw new SCException("Shape is not cannot be removed.");
}
```

I would have expected the method to be more like this:
```
public void Remove(IShape shape)
{
    if (!this.shapes.Contains(shape))
    {
        throw new SCException("Shape is not found.");
    }

    if (shape is IRemoveable removeable)
    {
        removeable.Remove();
    }
    else
    {
        throw new SCException("Shape cannot be removed.");
    }
}
```

**Comment by ashahabov** [comment] 2024-08-16 18:37
@pnoffke64, thank you for the bug report. I was able to reproduce this issue.

The problem is that the shape collection is immutable, meaning that the collection items are always recreated each time the collection is accessed. Therefore, two instances of `IShape` representing the same underlying shape are considered different.

As a solution, I suggest removing the `Remove()` method from the collection level and moving it to `IShape`. This way, each shape can remove itself.

**Closed** 2024-09-06 16:48 UTC
Labels: bug
