### ISSUE TITLE
File is not released

### ISSUE THREAD

**Issue by sureshmali** [ShapeCrawler/ShapeCrawler#149] opened 2021-07-30 07:41 UTC
```
IPresentation presentation = SCPresentation.Open(HostingEnvironment.MapPath("~/Template/Education_Template.pptx"), isEditable: true);

presentation.Close();
presentation.Dispose();
```

after close or dispose method the file opened is not released.

**Comment by adamshakhabov** [comment] 2021-07-30 09:00
Hi. Thank you for the report!

>  ... is not released

You mean the file is not accessed? For example, in the code below, the closed file is successfully deleted:

```
const string filePath = @"c:\temp\test.pptx";
IPresentation presentation = SCPresentation.Open(filePath, true);
presentation.Close();

File.Delete(filePath);
```

**Comment by sureshmali** [comment] 2021-07-30 09:20
No, I mean if the same method is called again. Exception is thrown, the file trying to open is already open.

**Comment by adamshakhabov** [comment] 2021-07-30 10:07
Was able to reproduce! Will fix.

Many thanks.

**Comment by sureshmali** [comment] 2021-07-30 10:27
Thanks

**Comment by adamshakhabov** [comment] 2021-07-30 16:17
The bug has been fixed in the **[v0.21.1](https://github.com/ShapeCrawler/ShapeCrawler/releases/tag/v0.21.1)** version.

Please, feel free to re-open the issue if this still does not work correctly.

**Comment by sureshmali** [comment] 2021-08-02 06:02
Thanks for the quick fix. I have tested it and is working as expected.

**Comment by ashahabov** [comment] 2024-09-06 10:00
Hello @tboulis,

could you please provide a sample of how you add table.

It works for me, for example, when I do this in the following way:

```C#
var pres = new Presentation();
pres.Slides[0].Shapes.AddTable(10, 10, 2, 2);

pres.SaveAs("result.pptx");
```

**Closed** 2024-09-06 16:18 UTC
Labels: bug
